### ISSUE TITLE
fill-fix branch:

### ISSUE THREAD

**Issue by ouboub** [mathworks/Emacs-MATLAB-Mode#15]
Hi
I updated the fill-fix branch.
- I merged default into the fill-fix branch, and reverted the conflicting files, matlab and mlint to the last commit in the default branch
- I added the most promising matlab-fill-paragraph to matlab.el in the fill-fix branch

more tests and improvements should be done, before merging fill-fix into default.

Uwe Brauer

**Comment by JohnC32** [comment]
Thanks. My schedule is a little full. I think I may have time in about two weeks to really dig into this.

**Comment by JohnC32** [comment]
Commit 864ff8a925a28f8dea04135ef228969bcb8bb301 on the fill-fix branch should fix the fill paragraph issues. It also contains tests to ensure we don't regress. 

Uwe - can you check this out and if good, merge into the default branch?

**Comment by ouboub** [comment]
>>> "JC" == John Ciolfi ***@***.***> writes:

> Commit 864ff8a925a28f8dea04135ef228969bcb8bb301 on the fill-fix branch
> should fix the fill paragraph issues. It also contains tests to ensure
> we don't regress.

> Uwe - can you check this out and if good, merge into the default branch?


Ok, but most likely only by tomorrow.
-- 
I strongly condemn Hamas heinous despicable pogroms/atrocities on Israel
I strongly condemn Putin's war of aggression against Ukraine.
I support to deliver weapons to Ukraine's military. 
I support the EU and NATO membership of Ukraine.

**Comment by JohnC32** [comment]
Thanks. Note, I moved your `test-fill-bug/fil_prob2.m` to `tests/fill-paragraph/fill_prob2.m` with a fill-column of 100. It's long-unfilled comment lines are programatically filled by metest.el, `metest-fill-paragraph` and compared against `tests/fill-paragraph/fill_prob2.m.expected.txt`. This made a good test case in addition to the existing tests.

**Comment by ouboub** [comment]
> Uwe - can you check this out and if good, merge into the default
> branch?
> 

Hi, bad news, there are still problems, I take the file **fill_prob2.m** found in `tests/fill-paragraph`
I put the cursor at the end of line

```matlab
        diff = 100;                                              % se toma un numero arbitrariamente grande para inicializar el error de la iteración simple
```
in other words at the word **simple** then I run `M-q`, `matlab-fill-comment-line` and I receive an error

```emacs-lisp
Debugger entered--Lisp error: (args-out-of-range #<buffer fill_prob2.m> 1 1)
  match-string(0)
  matlab-fill-comment-line()
  funcall-interactively(matlab-fill-comment-line)
  call-interactively(matlab-fill-comment-line nil nil)
  command-execute(matlab-fill-comment-line)

```

**Comment by JohnC32** [comment]
Hi Uwe,

I don't think you tested the fill-fix branch. Your stack trace is referencing the deleted matlab-fill-comment-line function. I  deleted it because it was broken and I found a better solution. Try:

```bash
mkdir test-fill-fix
cd test-fill-fix
git clone https://github.com/mathworks/Emacs-MATLAB-Mode.git
cd Emacs-MATLAB-Mode/
git checkout fill-fix
git branch
 # should show:
 #   default
 # * fill-fix
make clean
make lisp -j12
which matlab 
# should show full path to matlab
M=$(pwd)
env MATLABPATH=  PATH=/matlab-install/bin:$PATH  emacs -Q -L $M -l $M/matlab-autoload.el
```

Note, the last line "env ... emacs ..." invokes Emacs without your customizations.

See the examples in tests/fill-paragraph/*.m and the expected results *.m.expected.txt.

Within emacs use `M-q` anywhere. In code, it should do nothing. In comments it should fill them.

**Comment by ouboub** [comment]
> I don't think you tested the fill-fix branch. Your stack trace is
> referencing the deleted matlab-fill-comment-line function. I deleted
> it because it was broken and I found a better solution. Try:
> 

Actually I am on  the right branch and run `make clean` and `make` again, however I forgot to **restart emacs**, sigh, sorry.
I started to test and it looks quite good. Let me continue testing today and tomorrow, and then I will merge.

Sorry for the noise

**Comment by ouboub** [comment]
Filling has improved very much, the fix-fill has been merged into default.
