### ISSUE TITLE
Cleanup "cellbreak" faces and rename to section-break

### ISSUE THREAD

**Issue by JohnC32** [mathworks/Emacs-MATLAB-Mode#9]
There are two similar faces - matlab-cellbreak-face and matlab-sections-cellbreak-face that apply to "%% code sections" starts. Can we reduce these to one? It looks like matlab-cellbreak-face isn't used?

Also, this should be renamed to matlab-sections-break-face.

**Comment by Nidish96** [comment]
I've done the cleanup and added a PR ( #12  ). 
I've used the terminology `matlab-sections-section-break-face` since this makes it clear that this comes from the `matlab-sections` minor-mode.
